version: '3.8'

services:

  eshop:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: delight123
      MYSQL_DATABASE: ecommerce-on-cloud
      
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - keycloak-network

  redis-cart:
    image: redis:latest
    container_name: cart
    ports:
      - 6379:6379
    command: ["redis-server","--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - keycloak-network

  keycloak-db:
    image: mysql:latest
    container_name: keycloak-db
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    restart: unless-stopped
    volumes:
      - keycloak-db-data:/var/lib/mysql
    networks:
      - keycloak-network
     
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    command: [ "start-dev", "--import-realm" ]
    container_name: keycloak
    environment:
      # Keycloak Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: nimda
      # Network settings
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KC_PROXY_HEADERS: forwarded
      # Database settings
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_DATABASE: keycloak
    ports:
      - 9090:8080
    restart: unless-stopped
    depends_on:
      - keycloak-db
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - keycloak-network
  #resource-server:
    #build:
      #context: ..
      #dockerfile: Dockerfile
    #container_name: resource-server
    #ports:
      #- "8081:8081"
    #environment:
      #- SPRING_DATASOURCE_URL=jdbc:mysql://eshop:3306/ecommerce-on-cloud?useSSL=false&allowPublicKeyRetrieval=true
      #- SPRING_DATASOURCE_USERNAME=root
      #- SPRING_DATASOURCE_PASSWORD=delight123
      #- SPRING_REDIS_HOST=redis-cart
      #- SPRING_REDIS_PORT=6379
      #- SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:9090/realms/oauth2-resource-server
      #- REDIS_HOST=redis-cart
    #depends_on:
      #- eshop
      #- redis-cart
      #- keycloak
    #networks:
      #- keycloak-network

volumes:
  redis-data:
  keycloak-data:
  keycloak-db-data:
  mysql-data:

networks:
  keycloak-network:
    driver: bridge